//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vorrennung.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Doppelklick]")]
        public string FFmpeg {
            get {
                return ((string)(this["FFmpeg"]));
            }
            set {
                this["FFmpeg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\tmp")]
        public string Temp {
            get {
                return ((string)(this["Temp"]));
            }
            set {
                this["Temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double MinimaleBeschleunigung {
            get {
                return ((double)(this["MinimaleBeschleunigung"]));
            }
            set {
                this["MinimaleBeschleunigung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double MaximaleBeschleunigung {
            get {
                return ((double)(this["MaximaleBeschleunigung"]));
            }
            set {
                this["MaximaleBeschleunigung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.006")]
        public double Intensitaet {
            get {
                return ((double)(this["Intensitaet"]));
            }
            set {
                this["Intensitaet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.02")]
        public double Leise {
            get {
                return ((double)(this["Leise"]));
            }
            set {
                this["Leise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double Laut {
            get {
                return ((double)(this["Laut"]));
            }
            set {
                this["Laut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double MinimalePausenBeschleunigung {
            get {
                return ((double)(this["MinimalePausenBeschleunigung"]));
            }
            set {
                this["MinimalePausenBeschleunigung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Rueckwaertspruefung {
            get {
                return ((bool)(this["Rueckwaertspruefung"]));
            }
            set {
                this["Rueckwaertspruefung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ffmpegversuch2 {
            get {
                return ((string)(this["ffmpegversuch2"]));
            }
            set {
                this["ffmpegversuch2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double MaximalerAbfall {
            get {
                return ((double)(this["MaximalerAbfall"]));
            }
            set {
                this["MaximalerAbfall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double MinimalerAbfall {
            get {
                return ((double)(this["MinimalerAbfall"]));
            }
            set {
                this["MinimalerAbfall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Ableitungsglaettung {
            get {
                return ((double)(this["Ableitungsglaettung"]));
            }
            set {
                this["Ableitungsglaettung"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AbleitungBerueck {
            get {
                return ((bool)(this["AbleitungBerueck"]));
            }
            set {
                this["AbleitungBerueck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SolaVerwenden {
            get {
                return ((bool)(this["SolaVerwenden"]));
            }
            set {
                this["SolaVerwenden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Doppelklick]")]
        public string FFprobe {
            get {
                return ((string)(this["FFprobe"]));
            }
            set {
                this["FFprobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BevorzugterBeschleunigungsmodus {
            get {
                return ((int)(this["BevorzugterBeschleunigungsmodus"]));
            }
            set {
                this["BevorzugterBeschleunigungsmodus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DragDropErzeugen {
            get {
                return ((bool)(this["DragDropErzeugen"]));
            }
            set {
                this["DragDropErzeugen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EigeneFPS {
            get {
                return ((bool)(this["EigeneFPS"]));
            }
            set {
                this["EigeneFPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Fpswert {
            get {
                return ((int)(this["Fpswert"]));
            }
            set {
                this["Fpswert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int SolaSchritt {
            get {
                return ((int)(this["SolaSchritt"]));
            }
            set {
                this["SolaSchritt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SolaDiv {
            get {
                return ((int)(this["SolaDiv"]));
            }
            set {
                this["SolaDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SolaBer {
            get {
                return ((int)(this["SolaBer"]));
            }
            set {
                this["SolaBer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFFmpegToo {
            get {
                return ((bool)(this["UseFFmpegToo"]));
            }
            set {
                this["UseFFmpegToo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Dynaudnorm {
            get {
                return ((bool)(this["Dynaudnorm"]));
            }
            set {
                this["Dynaudnorm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskForSimultan {
            get {
                return ((bool)(this["AskForSimultan"]));
            }
            set {
                this["AskForSimultan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Expertenmodus {
            get {
                return ((bool)(this["Expertenmodus"]));
            }
            set {
                this["Expertenmodus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Beschleunigungslider {
            get {
                return ((int)(this["Beschleunigungslider"]));
            }
            set {
                this["Beschleunigungslider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Audioqualislider {
            get {
                return ((int)(this["Audioqualislider"]));
            }
            set {
                this["Audioqualislider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Pausenlaengeslider {
            get {
                return ((int)(this["Pausenlaengeslider"]));
            }
            set {
                this["Pausenlaengeslider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PruefePfade {
            get {
                return ((bool)(this["PruefePfade"]));
            }
            set {
                this["PruefePfade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtraFFmpegParams {
            get {
                return ((string)(this["ExtraFFmpegParams"]));
            }
            set {
                this["ExtraFFmpegParams"] = value;
            }
        }
    }
}
